# Prometheus configuration for monitoring the EC2 deployment
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

# Scrape configuration
scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Node.js application on EC2
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['18.136.197.156:3000'] # Replace with your EC2 public IP
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Monitor Node Exporter on EC2 (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['18.136.197.156:9100'] # Replace with your EC2 public IP
    scrape_interval: 15s
    scrape_timeout: 10s

# Optional: Add alerting rules
rule_files:
  # - "alert_rules.yml"

# Optional: Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093